### ISSUE TITLE
Create an Application Logo

### ISSUE THREAD

**Issue by HarshCasper** [UAceIt-Winter-of-Mentorship/Malaria-Detection#4]
## Description

Currently, we need a Logo for our Application which would be used on our Web Application Interface. 

# Tools

- Figma
- Adobe XD
- Adobe Photoshop 

## Additional Details

Logo Designs must be added in an appropriate form on the `assets/Logo-Design/` Directory. The basic criteria we are looking for are: 

- The logo should be optimized to a 500x500 Pixel Size.
- Transparent Background must be used. 
- Design Philosophy should be documented in the PR.

**Comment by ineffable23** [comment]
I would like to work on this issue please assign it to me.

**Comment by palaktyagi000** [comment]
I would like to work on this issue too, please give me some more information about it. May I use illustrator?

**Comment by HarshCasper** [comment]
Hi @palaktyagi000 

Please go ahead. Use whatever tool fits best with you.
